server{
    listen 80
    server_name localhost;

    localtion / {
        proxy_pass http://app-backend:5050;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote-addr;
        proxy_set_header X-Forwarded-For $proxy-add-x-forwarded-for
    }
}